version: 2

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: gomantics
    name: sx
  
  draft: false
  replace_existing_draft: true
  target_commitish: '{{ .Commit }}'
  footer: |
    
    ### Installation
    
    ```bash
    go get github.com/gomantics/sx@{{ .Tag }}
    ```

    ### Usage
    
    Import the library in your Go code:
    ```go
    import "github.com/gomantics/sx"
    ```
    
    **Full Changelog**: https://github.com/gomantics/sx/compare/{{ .PreviousTag }}...{{ .Tag }}
